const dirConfig ={
  base:'../static/remote-img/',
  dirArr:['env/', 'sat/', 'ascat/']
};

const config = {
  i20: [
    {urlBase:'https://www.data.jma.go.jp/fcd/yoho/data/wxchart/quick/', name:'ASAS_COLOR.pdf' , lastModified:'', dir:'env/'},
    {urlBase:'https://www.data.jma.go.jp/fcd/yoho/data/wxchart/quick/', name:'FSAS24_COLOR_ASIA.pdf' , lastModified:'', dir:'env/'},
    {urlBase:'https://www.data.jma.go.jp/fcd/yoho/data/wxchart/quick/', name:'FSAS48_COLOR_ASIA.pdf' , lastModified:'', dir:'env/'},
    {urlBase:'https://www.tropicaltidbits.com/analysis/ocean/', name:'cdas-sflux_sst_wpac_1.png', lastModified:'', dir:'env/'},//'last-modified'
    {urlBase:'https://www.tropicaltidbits.com/analysis/ocean/', name:'cdas-sflux_ssta_wpac_1.png', lastModified:'', dir:'env/'},
    {urlBase:'https://www.tropicaltidbits.com/analysis/ocean/', name:'cdas-sflux_ssta_global_1.png', lastModified:'', dir:'env/'},
    {urlBase:'http://www.oceanweather.com/data/South-China-Sea/', name:'WAVE000.GIF', lastModified:'', dir:'env/'},
    {urlBase:'http://www.oceanweather.com/data/NPAC-Western/', name:'WAVE000.GIF', lastModified:'', dir:'env/west-'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsvor.GIF' , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsconv.GIF', lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsdvg.GIF' , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsshr.GIF' , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmssht.GIF' , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmswv.GIF'  , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsir.GIF'  , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsdlm1.GIF'  , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsdlm2.GIF'  , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsdlm3.GIF'  , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsdlm4.GIF'  , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsdlm5.GIF'  , lastModified:'', dir:'env/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/winds/', name:'wgmsdlm6.GIF'  , lastModified:'', dir:'env/'},
    {urlBase:'http://www.ssd.noaa.gov/PS/TROP/TCFP/data/current/', name:'wp_rCUMP_048.gif', lastModified:'', dir:'env/'},
    {urlBase:'http://www.ssd.noaa.gov/PS/TROP/TCFP/data/current/', name:'wp_rTCFP_024.gif', lastModified:'', dir:'env/'},
    {urlBase:'http://www.ssd.noaa.gov/PS/TROP/TCFP/data/current/', name:'wp_rTCFP_048.gif', lastModified:'', dir:'env/'},
    {urlBase:'http://wxmaps.org/pix/'                            , name:'wpacpot.png'     , lastModified:'', dir:'env/'},
    {urlBase:'http://jtwc.gdmo.gq/jtwc/products/', name:'abpwsair.jpg', lastModified:'', dir:'env/'},//, retry:'any'},
    {urlBase:'http://models.weatherbell.com/sst/', name:'tcheat_wpac_2017.png', lastModified:'', dir:'env/'},
    {urlBase:'http://models.weatherbell.com/sst/', name:'wpac_cdas1.png', lastModified:'', dir:'env/'},
    {urlBase:'http://models.weatherbell.com/sst/', name:'wpac_cdas1_anom.png', lastModified:'', dir:'env/'},
    {urlBase:'http://www.cpc.ncep.noaa.gov/products/precip/CWlink/MJO/CLIVAR/', name:'ECMF_phase_51m_full.gif', lastModified:'', dir:'env/'},
    {urlBase:'http://www.cpc.ncep.noaa.gov/products/precip/CWlink/MJO/', name:'ensplume_full.gif', lastModified:'', dir:'env/'},
    {urlBase:'http://www.cpc.ncep.noaa.gov/products/precip/CWlink/ghazards/images/', name:'gth_full.png', lastModified:'', dir:'env/'},
   // {urlBase:'http://www.typhoon2000.ph/', name:'t2kgraphsat.gif', lastModified:'', dir:'env/'},
    {urlBase:'http://cmdp.ncc-cma.net/Monitoring/EastAsian/', name:'scs2idx.today.gif', lastModified:'', dir:'env/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds230.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds242.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds254.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds231.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds243.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds255.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds232.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds244.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds256.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds233.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds245.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBds257.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas230.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas242.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas254.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas231.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas243.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas255.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas232.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas244.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas256.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas233.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas245.png' , lastModified:'', dir:'ascat/'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_META/zooms/', name:'WMBas257.png' , lastModified:'', dir:'ascat/'},

    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds230.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds242.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds254.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds231.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds243.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds255.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds232.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds244.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds256.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds233.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds245.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBds257.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas230.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas242.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas254.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas231.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas243.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas255.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas232.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas244.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas256.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas233.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas245.png' , lastModified:'', dir:'ascat/B-'},
    {urlBase:'http://manati.star.nesdis.noaa.gov/ascat_images/cur_25km_METB/zooms/', name:'WMBas257.png' , lastModified:'', dir:'ascat/B-'},
  ],
  i6:[
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/images/kml/', name:'irbdgmskml.GIF', lastModified:'', dir:'sat/'},// 这个是不是有问题?
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/images/kml/', name:'yyirgms5.GIF'  , lastModified:'', dir:'sat/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/images/kml/', name:'yyirgms5n.GIF' , lastModified:'', dir:'sat/'},
    {urlBase:'http://tropic.ssec.wisc.edu/real-time/westpac/images/kml/', name:'yywvgms5.GIF'  , lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'vis-l.gif', lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'ir2-l.gif', lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'wv-l.gif' , lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'ir4-l.gif', lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'bd-l.gif' , lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'rb-l.gif' , lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'avn-l.gif', lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'rgb-l.jpg', lastModified:'', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/poes/twpac/', name:'ss85-l.jpg', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/poes/twpac/', name:'sswd-l.jpg', dir:'sat/'},
    {urlBase:'http://www.ssd.noaa.gov/poes/twpac/', name:'am89-l.jpg', dir:'sat/'},
    {urlBase:'http://rammb.cira.colostate.edu/ramsdis/online/images/latest/himawari-8/', name:'tropics_band_03.gif', dir:'sat/'},
    {urlBase:'http://rammb.cira.colostate.edu/ramsdis/online/images/latest/himawari-8/', name:'himawari-8_band_07_sector_06.gif', dir:'sat/'},
    {urlBase:'http://rammb.cira.colostate.edu/ramsdis/online/images/latest/himawari-8/', name:'tropics_band_08.gif', dir:'sat/'},
    {urlBase:'http://rammb.cira.colostate.edu/ramsdis/online/images/latest/himawari-8/', name:'himawari-8_band_13_sector_06.gif', dir:'sat/'},
  ],
  h1:[
   {urlBase:'http://www.typhoon2000.ph/', name:'t2kgraphsat.gif', lastModified:'', dir:'env/'},
  ],
  iTest:[
    {urlBase:'http://www.ssd.noaa.gov/jma/twpac/', name:'vis-l.gif', lastModified:'', dir:'sat/'},
  ]
};

module.exports = {
  config,
  dirConfig,
};

/* export {config,dirConfig};
export default {config,dirConfig}; */
